# Mac M1 Only
arch -x86_64 /usr/local/bin/brew install coreutils
arch -x86_64 /usr/local/bin/brew install binutils
arch -x86_64 /usr/local/bin/brew install diffutils
arch -x86_64 /usr/local/bin/brew install ed
arch -x86_64 /usr/local/bin/brew install findutils
arch -x86_64 /usr/local/bin/brew install gawk
arch -x86_64 /usr/local/bin/brew install gnu-indent
arch -x86_64 /usr/local/bin/brew install gnu-sed
arch -x86_64 /usr/local/bin/brew install gnu-tar
arch -x86_64 /usr/local/bin/brew install gnu-which
arch -x86_64 /usr/local/bin/brew install gnutls
arch -x86_64 /usr/local/bin/brew install grep
arch -x86_64 /usr/local/bin/brew install gzip
arch -x86_64 /usr/local/bin/brew install screen
arch -x86_64 /usr/local/bin/brew install watch
arch -x86_64 /usr/local/bin/brew install wdiff
arch -x86_64 /usr/local/bin/brew install wget
arch -x86_64 /usr/local/bin/brew install less
