# Owner: Solomon Xie 
# Email: solomonxiewise@gmail.com 
# Preload dependencies: 
#     # Plugin: Syntax-highlighting
#     $ git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
#     # Plugin: zsh-autosuggestions
#     $ git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
#     # Theme: Agnoster
#     $ wget https://raw.githubusercontent.com/agnoster/agnoster-zsh-theme/master/agnoster.zsh-theme -P ~/.oh-my-zsh/themes/
#     # Theme: Powerlevel9k
#     $ git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
# 
# Commands: 
# 
# 
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes 
# This must be placed at first, or it won't show any theme 
export TERM="xterm-256color" 
POWERLEVEL9K_MODE='nerdfont-complete' #PowerLevel9k 字体字体模式设定 (必须放在主题之前） 
ZSH_THEME="powerlevel9k/powerlevel9k" 
#ZSH_THEME="agnoster" 
 
# Path to oh-my-zsh installation. 
export ZSH=~/.oh-my-zsh 
plugins=( 
  git, 
  zsh-autosuggestions, 
  colored-man-pages 
) 
source $ZSH/oh-my-zsh.sh 

# 引用不方便公开的本地配置文件
source $HOME/.zshrc.extension
 
 
# hide User @ Hostname 
DEFAULT_USER=$USER 
# or  
#prompt_context() { 
#} 
 
 
 
# ----- User configuration ----- 
 
export PATH="/usr/local/sbin:$PATH"  # 有些软件安装到了这个位置 需要这个环境变量加入进来 
export PATH="/usr/local/opt/python/libexec/bin:$PATH" 
export EDITOR=vim 
 
 
 
# ==== Theme Settings ==== 
# PowerLevel9k 
# System status Elements (background_jobs battery context dir dir_writable disk_usage history host ip vpn_ip public_ip load os_icon ram root_indicator status swap time user vi_mode ssh) 
#左侧栏目显示的要素（指定的关键字参考官网） 
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh os_icon context dir vcs virtualenv) 
#右侧栏目显示的要素 
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time) 
#时间格式 
#POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S %d.%m.%y}" 
POWERLEVEL9K_CUSTOM_VIRTUALENV="red" 
#新起一行显示命令 (推荐！极其方便） 
POWERLEVEL9K_PROMPT_ON_NEWLINE=true 
#右侧状态栏不和目录在一行，而是和命令在同一行 
#POWERLEVEL9K_RPROMPT_ON_NEWLINE=true 
# 与上面的命令隔开一行 
#POWERLEVEL9K_PROMPT_ADD_NEWLINE=true 
#缩短目录层级 
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
#缩短目录策略：隐藏上层目录中间的字 
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle" 
# 显示目录是否可写 
POWERLEVEL9K_DIR_SHOW_WRITABLE=true 
#添加连接上下连接箭头更方便查看 
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱" 
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳ " 
#新的命令与上面的命令隔开一行 
#POWERLEVEL9K_PROMPT_ADD_NEWLINE=true 
#一般图标色彩指定 
POWERLEVEL9K_OS_ICON_BACKGROUND="black" 
POWERLEVEL9K_OS_ICON_FOREGROUND="white" 
POWERLEVEL9K_DIR_HOME_FOREGROUND="black" 
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="black" 
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="black" 
POWERLEVEL9K_TIME_FOREGROUND="006" 
POWERLEVEL9K_TIME_BACKGROUND="235" 
POWERLEVEL9K_STATUS_OK_FOREGROUND="green" 
POWERLEVEL9K_STATUS_OK_BACKGROUND="236" 
#Git仓库状态的色彩指定 
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green' 
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black' 
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow' 
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black' 
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red' 
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black' 
#Icons图标指定 
#POWERLEVEL9K_HOME_ICON='' 
#POWERLEVEL9K_HOME_SUB_ICON='' 
#POWERLEVEL9K_FOLDER_ICON='' 
# Git(vcs) settings 
#POWERLEVEL9K_SHOW_CHANGESET=true 
 
 

 
# =====================================
# This must be at the end of ~/.zshrc 
source "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
